#
# Copyright (C) 2015 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Notice: this works only with Google's Goma build infrastructure.
ifneq ($(USE_GOMA),)
  # Check if USE_NINJA is defined because GNU make won't work well
  # with goma. Note this file is evaluated twice, once with
  # USE_NINJA=true by GNU make and once with USE_NINJA=false by kati
  # which is invoked by GNU make. So, we cannot test the value of
  # USE_NINJA.
  ifndef USE_NINJA
    $(error USE_GOMA=true works only with USE_NINJA=true)
  endif

  ifdef GOMA_DIR
    goma_dir := $(GOMA_DIR)
  else
    goma_dir := $(HOME)/goma
  endif
  goma_ctl := $(goma_dir)/goma_ctl.py
  goma_cc := $(goma_dir)/gomacc

  $(if $(wildcard $(goma_ctl)),, \
   $(warning You should have goma in $$GOMA_DIR or $(HOME)/goma) \
   $(error See go/ma/how-to-use-goma/how-to-use-goma-for-android for detail))

  # Append gomacc to existing *_WRAPPER variables so it's possible to
  # use both ccache and gomacc.
  CC_WRAPPER := $(strip $(CC_WRAPPER) $(goma_cc))
  CXX_WRAPPER := $(strip $(CXX_WRAPPER) $(goma_cc))

  # Ninja file generated by kati uses this for remote jobs (i.e.,
  # commands which contain gomacc). Note the parallelism of all other
  # jobs will be limited the number of cores.
  KATI_REMOTE_NUM_JOBS_FLAG := --remote_num_jobs=500

  # gomacc can start goma client's daemon process automatically, but
  # it is safer and faster to start up it beforehand. We run this as a
  # background process so this won't slow down the build.
  $(shell $(goma_ctl) ensure_start &> /dev/null &)

  goma_cc :=
  goma_ctl :=
  goma_dir :=
endif
