#!/bin/bash

set -ex

export FINA_BUG_ID='0'

export FINA_PLATFORM_CODENAME='UpsideDownCake'
export FINA_PLATFORM_CODENAME_JAVA='UPSIDE_DOWN_CAKE'
export FINA_PLATFORM_SDK_VERSION='34'
export FINA_PLATFORM_VERSION='14'

export FINA_BUILD_PREFIX='UP1A'

export FINA_MAINLINE_EXTENSION='6'
export FINA_MAINLINE_SDK_COMMIT_MESSAGE=''
export FINA_MAINLINE_SDK_BUILD_ID=0
