#!/bin/bash

echo "# begin build properties"
echo "# autogenerated by vendor_buildinfo.sh"

echo "ro.product.board=$TARGET_BOOTLOADER_BOARD_NAME"
echo "ro.board.platform=$TARGET_BOARD_PLATFORM"

echo "ro.vendor.product.manufacturer=$PRODUCT_MANUFACTURER"
echo "ro.vendor.product.model=$PRODUCT_MODEL"
echo "ro.vendor.product.brand=$PRODUCT_BRAND"
echo "ro.vendor.product.name=$PRODUCT_NAME"
echo "ro.vendor.product.device=$TARGET_DEVICE"

echo "# end build properties"
