#!/bin/bash

echo "# begin build properties"
echo "# autogenerated by vendor_buildinfo.sh"

echo "ro.product.board=$TARGET_BOOTLOADER_BOARD_NAME"
echo "ro.board.platform=$TARGET_BOARD_PLATFORM"

echo "# end build properties"
